export default [
  { char: '她', pinyin: 'tā', def: 'she' },
  { char: '叫', pinyin: 'jiào', def: 'to be called' },
  { char: '什', pinyin: 'shén', def: 'part of 什么 (what)' },
  { char: '么', pinyin: 'me', def: 'part of 什么 (what)' },
  { char: '名', pinyin: 'míng', def: 'name' },
  { char: '字', pinyin: 'zì', def: 'character / name' },
  { char: '请', pinyin: 'qǐng', def: 'please' },
  { char: '问', pinyin: 'wèn', def: 'to ask' },
  { char: '贵', pinyin: 'guì', def: 'honorable (polite prefix)' },
  { char: '姓', pinyin: 'xìng', def: 'surname' },
  { char: '王', pinyin: 'wáng', def: 'Wang (surname)' },
  { char: '李', pinyin: 'lǐ', def: 'Li (surname)' },
  { char: '大', pinyin: 'dà', def: 'big' },
  { char: '小', pinyin: 'xiǎo', def: 'small' },
  { char: '上', pinyin: 'shàng', def: 'up / above' },
  { char: '下', pinyin: 'xià', def: 'down / below' },
  { char: '你', pinyin: 'nǐ', def: 'you' },
  { char: '我', pinyin: 'wǒ', def: 'I / me' },
  { char: '他', pinyin: 'tā', def: 'he' },
  { char: '好', pinyin: 'hǎo', def: 'good (used in 你好, hello)' },
  { char: '是', pinyin: 'shì', def: 'to be / is' },
  { char: '耶鲁', pinyin: 'Yēlǔ', def: 'Yale' },
  { char: '学', pinyin: 'xué', def: 'to study' },
  { char: '生', pinyin: 'shēng', def: 'person / pupil' },
  { char: '再见', pinyin: 'zàijiàn', def: 'goodbye' },
]
