export default [
  { char: '没', pinyin: 'méi', def: 'not (used with 有, to not have)' },
  { char: '高', pinyin: 'gāo', def: 'tall / high' },
  { char: '家', pinyin: 'jiā', def: 'family / home' },
  { char: '儿', pinyin: 'ér', def: 'son; diminutive suffix (used in 儿子)' },
  { char: '几', pinyin: 'jǐ', def: 'how many / several' },
  { char: '两', pinyin: 'liǎng', def: 'two (of something), a couple' },
  { char: '和', pinyin: 'hé', def: 'and / with' },
  { char: '作', pinyin: 'zuò', def: 'to do / to make (used in 工作, work)' },
  { char: '律', pinyin: 'lǜ', def: 'law / rule (used in 法律, law)' },
  { char: '都', pinyin: 'dōu', def: 'all / both' },
  { char: '爱', pinyin: 'ài', def: 'to love' },
  { char: '呢', pinyin: 'ne', def: 'question particle (softens a question)' },
  { char: '医', pinyin: 'yī', def: 'medicine / doctor (used in 医生)' },
  { char: '白', pinyin: 'bái', def: 'white' },
  { char: '英', pinyin: 'yīng', def: 'used in 英语 (English) / 英国 (Britain)' },
  { char: '号', pinyin: 'hào', def: 'number / day of the month' },
  { char: '星', pinyin: 'xīng', def: 'star (used in 星期, week)' },
  { char: '期', pinyin: 'qī', def: 'period of time (used in 星期, week)' },
  { char: '今', pinyin: 'jīn', def: 'now / this (used in 今天, 今年)' },
  { char: '年', pinyin: 'nián', def: 'year' },
  { char: '天', pinyin: 'tiān', def: 'day / sky (used in 今天, today)' },
  { char: '多', pinyin: 'duō', def: 'many / much' },
  { char: '岁', pinyin: 'suì', def: 'year (of age)' },
  { char: '吃', pinyin: 'chī', def: 'to eat' },
  { char: '饭', pinyin: 'fàn', def: '(cooked) rice / meal' },
  { char: '怎', pinyin: 'zěn', def: 'used in 怎么 (how)' },
  { char: '样', pinyin: 'yàng', def: 'kind / way (used in 怎样, how)' },
  { char: '太', pinyin: 'tài', def: 'too / extremely' },
  { char: '谢', pinyin: 'xiè', def: 'thanks (used in 谢谢)' },
  { char: '了', pinyin: 'le', def: 'particle marking completion / change' },
]
