export default [
  { char: '先生', pinyin: 'xiānsheng', def: 'Mr. / sir; also "husband"' },
  { char: '朋', pinyin: 'péng', def: 'friend (used in 朋友)' },
  { char: '友', pinyin: 'yǒu', def: 'friend' },
  { char: '的', pinyin: 'de', def: "possessive/attributive particle ('s / of)" },
  { char: '那', pinyin: 'nà', def: 'that' },
  { char: '不', pinyin: 'bù', def: 'not / no' },
  { char: '老', pinyin: 'lǎo', def: 'old' },
  { char: '师', pinyin: 'shī', def: 'teacher / master (used in 老师)' },
  { char: '吗', pinyin: 'ma', def: 'question particle' },
  { char: '也', pinyin: 'yě', def: 'also' },
  { char: '北京', pinyin: 'Běijīng', def: 'Beijing' },
  { char: '美', pinyin: 'měi', def: 'beautiful / pretty' },
  { char: '照', pinyin: 'zhào', def: 'to take a photo / to shine' },
  { char: '片', pinyin: 'piàn', def: 'piece / slice (used in 照片, photo)' },
  { char: '这', pinyin: 'zhè', def: 'this' },
  { char: '个', pinyin: 'gè', def: 'measure word (general classifier)' },
  { char: '孩', pinyin: 'hái', def: 'part of 孩子 (child)' },
  { char: '谁', pinyin: 'shéi', def: 'who' },
  { char: '爸', pinyin: 'bà', def: 'dad' },
  { char: '妈', pinyin: 'mā', def: 'mom' },
  { char: '哥', pinyin: 'gē', def: 'older brother' },
  { char: '弟', pinyin: 'dì', def: 'younger brother' },
  { char: '男', pinyin: 'nán', def: 'male' },
  { char: '女', pinyin: 'nǚ', def: 'female' },
  { char: '有', pinyin: 'yǒu', def: 'to have' },
]
