export default [
  { char: '请', pinyin: 'qǐng', def: 'please' },
  { char: '问', pinyin: 'wèn', def: 'to ask' },
  { char: '贵', pinyin: 'guì', def: 'honorable (polite prefix)' },
  { char: '姓', pinyin: 'xìng', def: 'surname' },
  { char: '王', pinyin: 'wáng', def: 'Wang (surname)' },
  { char: '李', pinyin: 'lǐ', def: 'Li (surname)' },
  { char: '先生', pinyin: 'xiānsheng', def: 'Mr. / sir; also "husband"' },
  { char: '她', pinyin: 'tā', def: 'she' },
  { char: '叫', pinyin: 'jiào', def: 'to be called' },
  { char: '什', pinyin: 'shén', def: 'part of 什么 (what)' },
  { char: '么', pinyin: 'me', def: 'part of 什么 (what)' },
  { char: '名', pinyin: 'míng', def: 'name' },
  { char: '字', pinyin: 'zì', def: 'character / name' },
  { char: '学', pinyin: 'xué', def: 'to study' },
  { char: '生', pinyin: 'shēng', def: 'person / pupil' },
  { char: '再见', pinyin: 'zàijiàn', def: 'goodbye' },
  { char: '友', pinyin: 'yǒu', def: 'friend' },
  { char: '也', pinyin: 'yě', def: 'also' },
  { char: '耶鲁', pinyin: 'Yēlǔ', def: 'Yale' },
]
