export default [
  { char: '喜', pinyin: 'xǐ', def: 'to be fond of (used in 喜欢, to like)' },
  { char: '欢', pinyin: 'huān', def: 'happy / joyful (used in 喜欢, to like)' },
  { char: '菜', pinyin: 'cài', def: 'vegetable / dish (food)' },
  { char: '还', pinyin: 'hái', def: 'still / also' },
  { char: '可', pinyin: 'kě', def: 'can / may (used in 可以)' },
  { char: '们', pinyin: 'men', def: 'plural suffix (used in 你们, 我们)' },
  { char: '点', pinyin: 'diǎn', def: "o'clock / point" },
  { char: '办', pinyin: 'bàn', def: 'to handle / to manage' },
  { char: '晚', pinyin: 'wǎn', def: 'evening / late' },
  { char: '现', pinyin: 'xiàn', def: 'now (used in 现在)' },
  { char: '在', pinyin: 'zài', def: 'at / in; to be located at' },
  { char: '刻', pinyin: 'kè', def: 'quarter hour / moment' },
  { char: '事', pinyin: 'shì', def: 'matter / thing' },
  { char: '很', pinyin: 'hěn', def: 'very' },
  { char: '忙', pinyin: 'máng', def: 'busy' },
  { char: '明', pinyin: 'míng', def: 'bright; next (used in 明天, tomorrow)' },
  { char: '因', pinyin: 'yīn', def: 'because / cause (used in 因为)' },
  { char: '为', pinyin: 'wèi', def: 'for / because of (used in 因为)' },
  { char: '认', pinyin: 'rèn', def: 'to recognize (used in 认识)' },
  { char: '识', pinyin: 'shí', def: 'to know / to recognize (used in 认识)' },
  { char: '同', pinyin: 'tóng', def: 'same / together (used in 同学, classmate)' },
  { char: '周', pinyin: 'zhōu', def: 'week' },
  { char: '打', pinyin: 'dǎ', def: 'to hit / to play (used in 打球)' },
  { char: '球', pinyin: 'qiú', def: 'ball' },
  { char: '看', pinyin: 'kàn', def: 'to look / to watch / to read' },
  { char: '电', pinyin: 'diàn', def: 'electricity (used in 电视, 电脑)' },
  { char: '视', pinyin: 'shì', def: 'to view / vision (used in 电视, television)' },
]
