export default [
  { char: '打', pinyin: 'dǎ', def: 'to hit / to play (as in sports)' },
  { char: '球', pinyin: 'qiú', def: 'ball' },
  { char: '看', pinyin: 'kàn', def: 'to look / to watch / to read' },
  { char: '电', pinyin: 'diàn', def: 'electricity' },
  { char: '视', pinyin: 'shì', def: 'to view / vision (as in "television")' },
  { char: '唱', pinyin: 'chàng', def: 'to sing' },
  { char: '歌', pinyin: 'gē', def: 'song' },
  { char: '跳', pinyin: 'tiào', def: 'to jump (as in "to dance")' },
  { char: '舞', pinyin: 'wǔ', def: 'dance' },
  { char: '音', pinyin: 'yīn', def: 'sound (as in "music")' },
  { char: '乐', pinyin: 'yuè', def: 'music; also lè, happy' },
  { char: '听', pinyin: 'tīng', def: 'to listen' },
  { char: '书', pinyin: 'shū', def: 'book' },
  { char: '对', pinyin: 'duì', def: 'correct / right; toward' },
  { char: '时', pinyin: 'shí', def: 'time' },
  { char: '后', pinyin: 'hòu', def: 'after / behind' },
  { char: '影', pinyin: 'yǐng', def: 'shadow (as in "movie")' },
  { char: '常', pinyin: 'cháng', def: 'often' },
  { char: '去', pinyin: 'qù', def: 'to go' },
  { char: '外', pinyin: 'wài', def: 'outside (as in "foreign")' },
  { char: '客', pinyin: 'kè', def: 'guest' },
  { char: '昨', pinyin: 'zuó', def: 'yesterday' },
  { char: '所', pinyin: 'suǒ', def: 'place (as in "therefore")' },
  { char: '久', pinyin: 'jiǔ', def: 'a long time' },
  { char: '错', pinyin: 'cuò', def: 'wrong / mistake (as in "not bad")' },
  { char: '想', pinyin: 'xiǎng', def: 'to think / to want to' },
  { char: '觉', pinyin: 'jué', def: 'to feel' },
  { char: '得', pinyin: 'de', def: 'structural particle' },
]
