export default [
  { char: '今', pinyin: 'jīn', def: 'now / this (as in "today", "this year")' },
  { char: '年', pinyin: 'nián', def: 'year' },
  { char: '天', pinyin: 'tiān', def: 'day / sky (as in "today")' },
  { char: '多', pinyin: 'duō', def: 'many / much' },
  { char: '岁', pinyin: 'suì', def: 'year (of age)' },
  { char: '吃', pinyin: 'chī', def: 'to eat' },
  { char: '饭', pinyin: 'fàn', def: '(cooked) rice / meal' },
  { char: '怎', pinyin: 'zěn', def: 'no standalone meaning (forms the word for "how")' },
  { char: '样', pinyin: 'yàng', def: 'kind / way (as in "how")' },
  { char: '太', pinyin: 'tài', def: 'too / extremely' },
  { char: '谢', pinyin: 'xiè', def: 'thanks' },
  { char: '了', pinyin: 'le', def: 'particle marking completion / change' },
  { char: '喜', pinyin: 'xǐ', def: 'to be fond of (as in "to like")' },
  { char: '欢', pinyin: 'huān', def: 'happy / joyful (as in "to like")' },
  { char: '菜', pinyin: 'cài', def: 'vegetable / dish (food)' },
  { char: '还', pinyin: 'hái', def: 'still / also' },
  { char: '可', pinyin: 'kě', def: 'can / may' },
  { char: '们', pinyin: 'men', def: 'plural suffix (as in "you all", "we")' },
  { char: '点', pinyin: 'diǎn', def: "o'clock / point" },
  { char: '办', pinyin: 'bàn', def: 'to handle / to manage' },
  { char: '晚', pinyin: 'wǎn', def: 'evening / late' },
  { char: '现', pinyin: 'xiàn', def: 'now' },
  { char: '在', pinyin: 'zài', def: 'at / in; to be located at' },
  { char: '刻', pinyin: 'kè', def: 'quarter hour / moment' },
  { char: '事', pinyin: 'shì', def: 'matter / thing' },
  { char: '很', pinyin: 'hěn', def: 'very' },
  { char: '忙', pinyin: 'máng', def: 'busy' },
  { char: '明', pinyin: 'míng', def: 'bright; next (as in "tomorrow")' },
  { char: '因', pinyin: 'yīn', def: 'because / cause' },
  { char: '为', pinyin: 'wèi', def: 'for / because of' },
  { char: '认', pinyin: 'rèn', def: 'to recognize' },
  { char: '识', pinyin: 'shi', def: 'to know / to recognize (neutral tone here)' },
  { char: '同', pinyin: 'tóng', def: 'same / together (as in "classmate")' },
  { char: '周', pinyin: 'zhōu', def: 'week' },
]
