export default [
  { char: '照', pinyin: 'zhào', def: 'to take a photo / to shine' },
  { char: '片', pinyin: 'piàn', def: 'piece / slice (used in 照片, photo)' },
  { char: '这', pinyin: 'zhè', def: 'this' },
  { char: '个', pinyin: 'gè', def: 'measure word (general classifier)' },
  { char: '孩', pinyin: 'hái', def: 'part of 孩子 (child)' },
  { char: '谁', pinyin: 'shéi', def: 'who' },
  { char: '爸', pinyin: 'bà', def: 'dad' },
  { char: '妈', pinyin: 'mā', def: 'mom' },
  { char: '哥', pinyin: 'gē', def: 'older brother' },
  { char: '弟', pinyin: 'dì', def: 'younger brother' },
  { char: '男', pinyin: 'nán', def: 'male' },
  { char: '女', pinyin: 'nǚ', def: 'female' },
  { char: '有', pinyin: 'yǒu', def: 'to have' },
  { char: '没', pinyin: 'méi', def: 'not (used with 有, to not have)' },
  { char: '高', pinyin: 'gāo', def: 'tall / high' },
  { char: '家', pinyin: 'jiā', def: 'family / home' },
  { char: '儿', pinyin: 'ér', def: 'son; diminutive suffix (used in 儿子)' },
  { char: '几', pinyin: 'jǐ', def: 'how many / several' },
  { char: '两', pinyin: 'liǎng', def: 'two (of something), a couple' },
  { char: '和', pinyin: 'hé', def: 'and / with' },
  { char: '作', pinyin: 'zuò', def: 'to do / to make (used in 工作, work)' },
  { char: '律', pinyin: 'lǜ', def: 'law / rule (used in 法律, law)' },
  { char: '都', pinyin: 'dōu', def: 'all / both' },
  { char: '爱', pinyin: 'ài', def: 'to love' },
  { char: '呢', pinyin: 'ne', def: 'question particle (softens a question)' },
  { char: '医', pinyin: 'yī', def: 'medicine / doctor (used in 医生)' },
  { char: '白', pinyin: 'bái', def: 'white' },
  { char: '英', pinyin: 'yīng', def: 'used in 英语 (English) / 英国 (Britain)' },
  { char: '号', pinyin: 'hào', def: 'number / day of the month' },
  { char: '星', pinyin: 'xīng', def: 'star (used in 星期, week)' },
  { char: '期', pinyin: 'qī', def: 'period of time (used in 星期, week)' },
]
