export default [
  { char: '你', pinyin: 'nǐ', def: 'you' },
  { char: '好', pinyin: 'hǎo', def: 'good (used in 你好, hello)' },
  { char: '我', pinyin: 'wǒ', def: 'I / me' },
  { char: '是', pinyin: 'shì', def: 'to be / is' },
  { char: '耶鲁', pinyin: 'Yēlǔ', def: 'Yale' },
  { char: '学', pinyin: 'xué', def: 'to study' },
  { char: '生', pinyin: 'shēng', def: 'person / pupil' },
  { char: '再见', pinyin: 'zàijiàn', def: 'goodbye' },
  { char: '请', pinyin: 'qǐng', def: 'please' },
  { char: '问', pinyin: 'wèn', def: 'to ask' },
  { char: '贵', pinyin: 'guì', def: 'honorable (polite prefix)' },
  { char: '姓', pinyin: 'xìng', def: 'surname' },
  { char: '王', pinyin: 'wáng', def: 'Wang (surname)' },
  { char: '李', pinyin: 'lǐ', def: 'Li (surname)' },
  { char: '她', pinyin: 'tā', def: 'she' },
  { char: '叫', pinyin: 'jiào', def: 'to be called' },
  { char: '什', pinyin: 'shén', def: 'part of 什么 (what)' },
  { char: '么', pinyin: 'me', def: 'part of 什么 (what)' },
  { char: '名', pinyin: 'míng', def: 'name' },
  { char: '字', pinyin: 'zì', def: 'character / name' },
  { char: '大', pinyin: 'dà', def: 'big' },
  { char: '小', pinyin: 'xiǎo', def: 'small' },
  { char: '上', pinyin: 'shàng', def: 'up / above' },
  { char: '下', pinyin: 'xià', def: 'down / below' },
  { char: '他', pinyin: 'tā', def: 'he' },
  { char: '先生', pinyin: 'xiānsheng', def: 'Mr. / sir; also "husband"' },
  { char: '朋', pinyin: 'péng', def: 'friend (used in 朋友)' },
  { char: '友', pinyin: 'yǒu', def: 'friend' },
  { char: '的', pinyin: 'de', def: "possessive/attributive particle ('s / of)" },
  { char: '那', pinyin: 'nà', def: 'that' },
  { char: '不', pinyin: 'bù', def: 'not / no' },
  { char: '老', pinyin: 'lǎo', def: 'old' },
  { char: '师', pinyin: 'shī', def: 'teacher / master (used in 老师)' },
  { char: '吗', pinyin: 'ma', def: 'question particle' },
  { char: '也', pinyin: 'yě', def: 'also' },
  { char: '北京', pinyin: 'Běijīng', def: 'Beijing' },
  { char: '美', pinyin: 'měi', def: 'beautiful / pretty' },
]
