export default [
  { char: '打', pinyin: 'dǎ', def: 'to hit / to play (used in 打球)' },
  { char: '球', pinyin: 'qiú', def: 'ball' },
  { char: '看', pinyin: 'kàn', def: 'to look / to watch / to read' },
  { char: '电', pinyin: 'diàn', def: 'electricity (used in 电视, 电脑)' },
  { char: '视', pinyin: 'shì', def: 'to view / vision (used in 电视, television)' },
  { char: '唱', pinyin: 'chàng', def: 'to sing (used in 唱歌)' },
  { char: '歌', pinyin: 'gē', def: 'song (used in 唱歌, to sing)' },
  { char: '跳', pinyin: 'tiào', def: 'to jump (used in 跳舞)' },
  { char: '舞', pinyin: 'wǔ', def: 'dance (used in 跳舞, to dance)' },
  { char: '音', pinyin: 'yīn', def: 'sound (used in 音乐, music)' },
  { char: '乐', pinyin: 'yuè', def: 'music (used in 音乐); also lè, happy' },
  { char: '听', pinyin: 'tīng', def: 'to listen' },
  { char: '书', pinyin: 'shū', def: 'book' },
  { char: '对', pinyin: 'duì', def: 'correct / right; toward' },
  { char: '时', pinyin: 'shí', def: 'time (used in 时候)' },
  { char: '后', pinyin: 'hòu', def: 'after / behind (used in 以后, 后面)' },
  { char: '影', pinyin: 'yǐng', def: 'shadow (used in 电影, movie)' },
  { char: '常', pinyin: 'cháng', def: 'often' },
  { char: '去', pinyin: 'qù', def: 'to go' },
  { char: '外', pinyin: 'wài', def: 'outside (used in 外国, foreign)' },
  { char: '客', pinyin: 'kè', def: 'guest (used in 客人)' },
  { char: '昨', pinyin: 'zuó', def: 'yesterday (used in 昨天)' },
  { char: '所', pinyin: 'suǒ', def: 'place (used in 所以, therefore)' },
  { char: '久', pinyin: 'jiǔ', def: 'a long time' },
  { char: '错', pinyin: 'cuò', def: 'wrong / mistake (used in 不错, not bad)' },
  { char: '想', pinyin: 'xiǎng', def: 'to think / to want to' },
  { char: '觉', pinyin: 'jué', def: 'to feel (used in 觉得)' },
  { char: '得', pinyin: 'de', def: 'structural particle (used in 觉得, 说得)' },
]
